#!/bin/bash
#
# Proton-NV Configure Script
# NVIDIA-optimized Proton build for RTX 40/50 series + Open Kernel Module 580+
#

set -e

SRCDIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_NAME="${BUILD_NAME:-Proton-NV}"

# Proton-NV Version
PROTON_NV_VERSION="1.0"

# Upstream versions - update these to track latest
PROTON_COMMIT="${PROTON_COMMIT:-proton-experimental-bleeding-edge}"
WINE_COMMIT="${WINE_COMMIT:-}"
DXVK_COMMIT="${DXVK_COMMIT:-master}"
VKD3D_COMMIT="${VKD3D_COMMIT:-master}"
DXVK_NVAPI_COMMIT="${DXVK_NVAPI_COMMIT:-master}"

# Build configuration
STEAMRT_IMAGE="${STEAMRT_IMAGE:-ghcr.io/open-wine-components/umu-sdk:latest}"
CONTAINER="${CONTAINER:-}"
ENABLE_CCACHE="${ENABLE_CCACHE:-1}"

# NVIDIA-specific settings
NVIDIA_OPEN_DRIVER_MIN="580"
TARGET_GPU_ARCH="RTX40,RTX50"

usage() {
    cat <<EOF
Proton-NV Configure Script
===========================

Usage: ./configure.sh [OPTIONS]

Options:
    --build-name=NAME       Set build name (default: Proton-NV)
    --proton-commit=COMMIT  Proton upstream commit/branch (default: proton-experimental-bleeding-edge)
    --dxvk-commit=COMMIT    DXVK commit/branch (default: master)
    --vkd3d-commit=COMMIT   vkd3d-proton commit/branch (default: master)
    --container             Build inside container
    --no-ccache             Disable ccache
    --help                  Show this help

Environment Variables:
    STEAMRT_IMAGE           Container image for build (default: ghcr.io/open-wine-components/umu-sdk:latest)
    PROTON_NV_VERSION       Version string for this build

NVIDIA Optimizations:
    - Tuned for NVIDIA Open Kernel Module 580+
    - RTX 40/50 series optimizations
    - VK_NV_low_latency2 support (Reflex)
    - BAR1-aware memory allocations
    - CachyOS kernel scheduler tuning
    - Linux-tkg BORE scheduler support

EOF
    exit 0
}

# Parse arguments
for arg in "$@"; do
    case "$arg" in
        --build-name=*)
            BUILD_NAME="${arg#*=}"
            ;;
        --proton-commit=*)
            PROTON_COMMIT="${arg#*=}"
            ;;
        --dxvk-commit=*)
            DXVK_COMMIT="${arg#*=}"
            ;;
        --vkd3d-commit=*)
            VKD3D_COMMIT="${arg#*=}"
            ;;
        --container)
            CONTAINER=1
            ;;
        --no-ccache)
            ENABLE_CCACHE=0
            ;;
        --help|-h)
            usage
            ;;
        *)
            echo "Unknown option: $arg"
            usage
            ;;
    esac
done

echo "========================================"
echo "Proton-NV Build Configuration"
echo "========================================"
echo "Build Name:      $BUILD_NAME"
echo "Version:         $PROTON_NV_VERSION"
echo "Proton Commit:   $PROTON_COMMIT"
echo "DXVK Commit:     $DXVK_COMMIT"
echo "VKD3D Commit:    $VKD3D_COMMIT"
echo "Target GPUs:     $TARGET_GPU_ARCH"
echo "Min Driver:      NVIDIA Open $NVIDIA_OPEN_DRIVER_MIN+"
echo "Container:       ${CONTAINER:-native}"
echo "========================================"

# Generate Makefile
cat > Makefile <<EOF
# Generated by configure.sh - Do not edit manually
SRCDIR := $SRCDIR
BUILD_NAME := $BUILD_NAME
PROTON_NV_VERSION := $PROTON_NV_VERSION
PROTON_COMMIT := $PROTON_COMMIT
DXVK_COMMIT := $DXVK_COMMIT
VKD3D_COMMIT := $VKD3D_COMMIT
DXVK_NVAPI_COMMIT := $DXVK_NVAPI_COMMIT
STEAMRT_IMAGE := $STEAMRT_IMAGE
CONTAINER := $CONTAINER
ENABLE_CCACHE := $ENABLE_CCACHE
NVIDIA_OPEN_DRIVER_MIN := $NVIDIA_OPEN_DRIVER_MIN
TARGET_GPU_ARCH := $TARGET_GPU_ARCH

include \$(SRCDIR)/Makefile.in
EOF

echo ""
echo "Configuration complete. Run 'make' to build Proton-NV."
echo ""
echo "Build targets:"
echo "  make              - Full build"
echo "  make fetch        - Fetch upstream sources"
echo "  make patch        - Apply patches"
echo "  make build        - Build all components"
echo "  make install      - Install to compatibilitytools.d"
echo "  make clean        - Clean build artifacts"
echo ""
