# Generated by configure.sh - Do not edit manually
SRCDIR := /data/projects/proton-NV
BUILD_NAME := Proton-NV
PROTON_NV_VERSION := 1.1
PROTON_COMMIT := proton-experimental-bleeding-edge
DXVK_COMMIT := master
VKD3D_COMMIT := v3.0
DXVK_NVAPI_COMMIT := master
STEAMRT_IMAGE := ghcr.io/open-wine-components/umu-sdk:latest
CONTAINER :=
ENABLE_CCACHE := 1
NVIDIA_OPEN_DRIVER_MIN := 595
TARGET_GPU_ARCH := RTX40,RTX50

# Development targets (for testing unreleased features)
VKD3D_COMMIT_DEV := descriptor-heap-dev
VKD3D_PR_2805 := pull/2805/head

# Feature flags
ENABLE_DESCRIPTOR_HEAP := auto

include $(SRCDIR)/Makefile.in
